version: 2
jobs:
  build:
    working_directory: ~/circleci-python-flask
    docker:
    - image: circleci/python:3.6.4
    steps:
    - checkout # check out source code to working directory
    - run: sudo chown -R circleci:circleci /usr/local/bin
    - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
    - run:
      command: |
        sudo pip install pipenv
        pipenv install
    - run:
      command: pipenv run "test"
